In [28]:
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database',)).History will not be written to the database.

In [29]:
parole = pd.read_csv("https://github.com/napolux/paroleitaliane/raw/master/paroleitaliane/60000_parole_italiane.txt",
                     names = ['parola'])
parole.head()

     parola
0         a
1     abate
2     abati
3   abbagli
4  abbaglia

In [31]:
def canonica(s):
    return ''.join(sorted(s))

In [32]:
canonica("banana")

'aaabnn'

In [15]:
parole['firma'] = parole['parola'].apply(canonica)
parole

             parola         firma
0                 a             a
1             abate         aabet
2             abati         aabit
3           abbagli       aabbgil
4          abbaglia      aaabbgil
5         abbagliai     aaabbgiil
6        abbagliamo    aaabbgilmo
7        abbagliano    aaabbgilno
8        abbagliare    aaabbegilr
9        abbagliata    aaaabbgilt
10       abbagliate    aaabbegilt
11       abbagliati    aaabbgiilt
12       abbagliato    aaabbgilot
13       abbagliava    aaaabbgilv
14       abbagliavi    aaabbgiilv
15       abbagliavo    aaabbgilov
16       abbagliera    aaabbegilr
17       abbagliero    aabbegilor
18        abbaglino     aabbgilno
19         abbaglio      aabbgilo
20            abbai         aabbi
21           abbaia        aaabbi
22          abbaiai       aaabbii
23        abbaiammo     aaabbimmo
24         abbaiamo      aaabbimo
25        abbaiando     aaabbdino
26         abbaiano      aaabbino
27         abbaiare      aaabbeir
28       abbaiarono    aaabbinoor
29        abbaiasse     aaabbeiss
...             ...           ...
60423       zuccono       ccnoouz
60424         zuffa         affuz
60425         zuffe         effuz
60426       zuffola       afflouz
60427      zuffolai      affilouz
60428    zuffolammo    afflmmoouz
60429    zuffolando    adfflnoouz
60430     zuffolano     afflnoouz
60431     zuffolare     aeffloruz
60432    zuffolasse    aefflossuz
60433    zuffolassi    affilossuz
60434    zuffolaste    aefflostuz
60435    zuffolasti    affilostuz
60436     zuffolata     aafflotuz
60437     zuffolate     aefflotuz
60438     zuffolato     afflootuz
60439     zuffolava     aafflouvz
60440     zuffolavi     affilouvz
60441     zuffolavo     affloouvz
60442     zuffolera     aeffloruz
60443    zuffolerai    aeffiloruz
60444    zuffolerei    eeffiloruz
60445       zuffoli       ffilouz
60446    zuffoliamo    affilmoouz
60447     zuffolino     ffilnoouz
60448       zuffolo       ffloouz
60449         zuppa         appuz
60450         zuppe         eppuz
60451      zuppiera      aeippruz
60452  zuzzurellone  eellnoruuzzz

[60453 rows x 2 columns]

In [7]:
conteggio = parole.groupby("firma").size()

In [8]:
conteggio.head()

firma
'aaaipprr      1
'aacceellnr    1
'aaccehirr     1
'aacfiilt      1
'aacimoprr     1
dtype: int64

In [36]:
ordinati = conteggio.sort_values(ascending = False).head(1)
ordinati

firma
aeirstv    9
dtype: int64

In [37]:
ordinati.index

Index(['aeirstv'], dtype='object', name='firma')

In [38]:
list(ordinati.index)

['aeirstv']

In [39]:
anagrammi = parole[parole['firma'].isin(list(ordinati.index))]
anagrammi

        parola    firma
6519   avresti  aeirstv
38546  restavi  aeirstv
51759  stivare  aeirstv
53745  svitare  aeirstv
59231  versati  aeirstv
59334  vestira  aeirstv
59730  viraste  aeirstv
59844  vistare  aeirstv
59861  vistera  aeirstv

In [40]:
anagrammi.sort_values('firma')

        parola    firma
6519   avresti  aeirstv
38546  restavi  aeirstv
51759  stivare  aeirstv
53745  svitare  aeirstv
59231  versati  aeirstv
59334  vestira  aeirstv
59730  viraste  aeirstv
59844  vistare  aeirstv
59861  vistera  aeirstv

In [ ]:
a = input()